### ISSUE TITLE
RuntimeError: Error loading state dict for TransformerSrlSpan

### ISSUE THREAD

**Issue by creatorrr** [Riccorl/transformer-srl#10]
On running the example in `README.md`, getting the following error:
```bash
RuntimeError: Error loading state dict for TransformerSrlSpan
        Missing keys: ['transformer.embeddings.position_ids']
        Unexpected keys: []
```

(Model downloaded from the Dropbox link mentioned)

**Comment by creatorrr** [comment]
Environment:
```toml
python = "^3.8"
transformer-srl = "^2.5"
spacy = "2.3"
```
